on: [push, workflow_dispatch]

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: soloam/release-target
          ref: 'master'
          token:  ${{ secrets.TARGET_SOURCE_TOKEN }}
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Commit and push generated template
        run: |
          export COMMIT_MESSAGE="My Test Commit"
          git add .
          git commit -m "$COMMIT_MESSAGE"
          git push
